apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{.Values.cluster_name}}
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{.Values.cluster_name}}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{.Values.cluster_name}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{.Values.cluster_name}}
spec:
  
    values: |
      serviceCIDR: "{{.Values.serviceCIDR}}"
      service:
        type: {{.Values.service.type }}
      
        
      securityContext:
        runAsUser: 12345
        runAsNonRoot: true
      fsGroup: 12345
  kubernetesVersion: "{{.Values.kubernetes_version}}"