cluster_name: "test-vcluster"
chart_name: "null"
# chart_name: "vcluster-k8s"
chart_repo: "null"
chart_version: "null"
kubernetes_version: "1.24"
serviceCIDR: "172.20.0.0/16"
service:
  type: "LoadBalancer"
  loadBalancerSourceRanges: []
  loadBalancerSourceRangesString: ""